### PR TITLE
Change Preflight to exit when scripts call non-zero exit

### PR DESCRIPTION
**Pull request by Zolotkey**
Let me know if this works for you Graham.

### CODE REVIEW

**Comment by sheagcraig** [comment]
This looks fine from a code standpoint.

I guess I missed out on the context; my assumption based on what I'm seeing is that there are some preflights floating around that throw an exception, and you would like the checkin to stop unless preflight was run without exceptions?

**Comment by grahamgilbert** [comment]
The preflight script was eating errors produced by the child scripts in preflight.d. Some people may want to halt the munki run if their preflight doesn’t exit 0.

**Comment by sheagcraig** [comment]
That makes total sense; I'm just confused because you said some people may want to halt the run, which suggests that some people may want it to continue. This PR only accounts for the former. Should we add a preference? Or a disclaimer?

**Comment by Zolotkey** [comment]
I would say disclaimer. As the way coded, it keeps up with what preflight scripts are meant for from this wiki article for munki. 

https://github.com/munki/munki/wiki/Preflight-And-Postflight-Scripts

**Comment by sheagcraig** [comment]
@Zolotkey this looks great; can I trouble you to update off of the new tip?

**Pull request closed without merging**
